spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/freelanceplatform
    username: root
    password: 123456
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


#阿里云OSS
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: 4HySV82lHfq4LpGEpZwpb6JUFDe9by
    access-key-id: LTAI5t9mXMycWhhj4CUmXvXa
    bucket-name: webss-tliass
#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
server:
  port:
    8080